### ISSUE TITLE
娱乐时封禁玩家

### ISSUE THREAD

**Issue by NTF0513** [XLittleLeft/HelpSense#25]
你好，我遇到了一个问题
我作为服主在进行娱乐时，将scp友军伤害打开并将枪械给予后，那些互打的scp被服务器封禁了，我排查后觉得是该插件的问题，能否询问是这个插件的问题吗，如果是，请告诉我如何避免此类问题，能否单独关闭此功能，谢谢

**Comment by Raiden-Yayi** [comment]
似乎是服务器本身的友军伤害惩罚

**Comment by Raiden-Yayi** [comment]
可以在配置文件修改

**Comment by Raiden-Yayi** [comment]
> 可以在配置文件修改

在服务器的gameplay文件

**Comment by NTF0513** [comment]
谢谢你的回复，我现在改
